version: '3.8'


services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
